/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author grey
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ItemTitular = new javax.swing.JMenuItem();
        ItemCuenta = new javax.swing.JMenuItem();
        ItemMov = new javax.swing.JMenu();
        ItemMovimiento = new javax.swing.JMenuItem();
        jmenuConsultas = new javax.swing.JMenu();
        ItemConsultaCts = new javax.swing.JMenuItem();
        ItemConsultarMovimientos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ItemSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jMenu1.setText("Personas");

        ItemTitular.setText("Titular");
        jMenu1.add(ItemTitular);

        ItemCuenta.setText("Cuenta");
        jMenu1.add(ItemCuenta);

        jMenuBar1.add(jMenu1);

        ItemMov.setText("Movimientos");

        ItemMovimiento.setText("Movimiento");
        ItemMov.add(ItemMovimiento);

        jMenuBar1.add(ItemMov);

        jmenuConsultas.setText("Consultas");

        ItemConsultaCts.setText("Consultar Cuentas");
        jmenuConsultas.add(ItemConsultaCts);

        ItemConsultarMovimientos.setText("Consultar Movimientos");
        jmenuConsultas.add(ItemConsultarMovimientos);

        jMenuBar1.add(jmenuConsultas);

        jMenu2.setText("Salir");

        ItemSalir.setText("Salir");
        jMenu2.add(ItemSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem ItemConsultaCts;
    public javax.swing.JMenuItem ItemConsultarMovimientos;
    public javax.swing.JMenuItem ItemCuenta;
    public javax.swing.JMenu ItemMov;
    public javax.swing.JMenuItem ItemMovimiento;
    public javax.swing.JMenuItem ItemSalir;
    public javax.swing.JMenuItem ItemTitular;
    public javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmenuConsultas;
    // End of variables declaration//GEN-END:variables
}
